# Informazioni sul Sito
title: CleverPocket
author: Oleksandr Bihansky
email: cleverpocket.info@gmail.com
description: "Independent developer focused on minimalist mobile&nbsp;apps for&nbsp;specific&nbsp;use&nbsp;cases."

# URL e Link
url: "https://cleverpocket.app"
baseurl: "" # Lascialo vuoto se il sito è nel dominio principale

# Impostazioni di Build
markdown: kramdown
theme: minima # Opzionale, se vuoi un tema di base, ma noi useremo il tuo stile personalizzato
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

 # Banner di Manutenzione
 maintenance_mode: true
 maintenance_message: "Maintenance in progress. Some features may be temporarily unavailable."